### ISSUE TITLE
Module too large

### ISSUE THREAD

**Issue by linky00** [SVendittelli/MMM-wordnik#2]
This module, whilst awesome, is too large horizontally and stretches all other modules. Is there a way to change this / could you add a config for this?

**Comment by SVendittelli** [comment]
In MMM-wordnik.js, change dictWrap.style.maxWidth = '50%';

For the configuration, feel free to make a pull request!

**Comment by linky00** [comment]
Thank you! Sorry, pretty new to MM, and participating in GitHub for that matter...

**Comment by linky00** [comment]
I tried changing this, but it only changed the width of the text in the module itself. All the other modules stayed stretched for some reason?

**Comment by linky00** [comment]
Actually, I think the problem might not be your module. I think it might be another one that's acting up... I'll look into fixing that one. Sorry if I got you involved in something that wasn't the problem!

UPDATE: I can't figure out what it is. The module I'm talking about is https://github.com/AdamMoses-GitHub/MMM-TwitterTrendsByPlace, whenever I load the wordnik module with it, it expands greatly for seemingly no reason, whilst the wordnik module stays perfectly contained. Here is what it looks like: http://imgur.com/a/MqKOd
